#    utils - utility library
#    Copyright (c) 2021-2022 on-keyday (https://github.com/on-keyday)
#    Released under the MIT license
#    https://opensource.org/licenses/mit-license.php
version: "3"
services:
  linux_test: 
    build: .
    ports:
      - "8092:8092"
    container_name: utils
    tty: true
    stdin_open: true
