#    utils - utility library
#    Copyright (c) 2021-2023 on-keyday (https://github.com/on-keyday)
#    Released under the MIT license
#    https://opensource.org/licenses/mit-license.php
version: "3"
services:
  linux_test:
    build: .
    ports:
      - "8092:8092"
    container_name: utils
    tty: true
    stdin_open: true
    volumes:
      - ./src:/usr/utilsdev/workspace/src:cached
      - ./build:/usr/utilsdev/workspace/build:cached
      - ./CMakeLists.txt:/usr/utilsdev/workspace/CMakeLists.txt:cached
      - ./.vscode/settings.json:/usr/utilsdev/workspace/.vscode/settings.json:cached
      - ./docker_vscode/tasks.json:/usr/utilsdev/workspace/.vscode/tasks.json:cached
      - ./docker_vscode/launch.json:/usr/utilsdev/workspace/.vscode/launch.json:cached
      - ./shell:/usr/utilsdev/workspace/shell:cached
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

volumes:
  src:
