/*
    utils - utility library
    Copyright (c) 2021-2022 on-keyday (https://github.com/on-keyday)
    Released under the MIT license
    https://opensource.org/licenses/mit-license.php
*/

// Code generated by ifacegen (https://github.com/on-keyday/utils)

#pragma once
#include "../helper/deref.h"
#include <functional>
#include "token.h"

#ifndef NOVTABLE__
#ifdef _WIN32
#define NOVTABLE__ __declspec(novtable)
#else
#define NOVTABLE__
#endif
#endif

namespace utils {
    namespace parser {
        template <typename string>
        struct error {
           private:
            struct NOVTABLE__ interface__ {
                virtual string Error() = 0;
                virtual Pos pos() = 0;
                virtual const void* raw__(const std::type_info&) const = 0;

                virtual ~interface__() {}
            };

            template <class T__>
            struct implements__ : interface__ {
                T__ t_holder_;

                template <class V__>
                implements__(V__&& args)
                    : t_holder_(std::forward<V__>(args)) {}

                string Error() override {
                    auto t_ptr_ = utils::helper::deref(this->t_holder_);
                    if (!t_ptr_) {
                        return string{};
                    }
                    return t_ptr_->Error();
                }

                Pos pos() override {
                    auto t_ptr_ = utils::helper::deref(this->t_holder_);
                    if (!t_ptr_) {
                        return Pos{};
                    }
                    return t_ptr_->pos();
                }

                const void* raw__(const std::type_info& info__) const override {
                    if (info__ != typeid(T__)) {
                        return nullptr;
                    }
                    return reinterpret_cast<const void*>(std::addressof(t_holder_));
                }
            };

            interface__* iface = nullptr;

           public:
            constexpr error() {}

            constexpr error(std::nullptr_t) {}

            template <class T__>
            error(T__&& t) {
                static_assert(!std::is_same_v<std::decay_t<T__>, error>, "can't accept same type");
                if (!utils::helper::deref(t)) {
                    return;
                }
                iface = new implements__<std::decay_t<T__>>(std::forward<T__>(t));
            }

            error(error&& in) {
                iface = in.iface;
                in.iface = nullptr;
            }

            error& operator=(error&& in) {
                if (this == std::addressof(in)) return *this;
                delete iface;
                iface = in.iface;
                in.iface = nullptr;
                return *this;
            }

            explicit operator bool() const {
                return iface != nullptr;
            }

            bool operator==(std::nullptr_t) const {
                return iface == nullptr;
            }

            ~error() {
                delete iface;
            }

            string Error() {
                return iface ? iface->Error() : string{};
            }

            Pos pos() {
                return iface ? iface->pos() : Pos{};
            }

            template <class T__>
            const T__* type_assert() const {
                if (!iface) {
                    return nullptr;
                }
                return reinterpret_cast<const T__*>(iface->raw__(typeid(T__)));
            }

            template <class T__>
            T__* type_assert() {
                if (!iface) {
                    return nullptr;
                }
                return reinterpret_cast<T__*>(const_cast<void*>(iface->raw__(typeid(T__))));
            }

            error(const error&) = delete;

            error& operator=(const error&) = delete;
        };

        template <typename Input, typename String, typename Kind, template <typename...> typename Vec>
        struct Func {
           private:
            struct NOVTABLE__ interface__ {
                virtual bool operator()(Sequencer<Input>& seq, wrap::shared_ptr<Token<String, Kind, Vec>>& tok, int flag, Pos& pos, error<String>& err) = 0;
                virtual const void* raw__(const std::type_info&) const = 0;

                virtual ~interface__() {}
            };

            template <class T__>
            struct implements__ : interface__ {
                T__ t_holder_;

                template <class V__>
                implements__(V__&& args)
                    : t_holder_(std::forward<V__>(args)) {}

                bool operator()(Sequencer<Input>& seq, wrap::shared_ptr<Token<String, Kind, Vec>>& tok, int flag, Pos& pos, error<String>& err) override {
                    auto t_ptr_ = utils::helper::deref(this->t_holder_);
                    if (!t_ptr_) {
                        throw std::bad_function_call();
                    }
                    return (*t_ptr_)(seq, tok, flag, pos, err);
                }

                const void* raw__(const std::type_info& info__) const override {
                    if (info__ != typeid(T__)) {
                        return nullptr;
                    }
                    return reinterpret_cast<const void*>(std::addressof(t_holder_));
                }
            };

            interface__* iface = nullptr;

           public:
            constexpr Func() {}

            constexpr Func(std::nullptr_t) {}

            template <class T__>
            Func(T__&& t) {
                static_assert(!std::is_same_v<std::decay_t<T__>, Func>, "can't accept same type");
                if (!utils::helper::deref(t)) {
                    return;
                }
                iface = new implements__<std::decay_t<T__>>(std::forward<T__>(t));
            }

            Func(Func&& in) {
                iface = in.iface;
                in.iface = nullptr;
            }

            Func& operator=(Func&& in) {
                if (this == std::addressof(in)) return *this;
                delete iface;
                iface = in.iface;
                in.iface = nullptr;
                return *this;
            }

            explicit operator bool() const {
                return iface != nullptr;
            }

            bool operator==(std::nullptr_t) const {
                return iface == nullptr;
            }

            ~Func() {
                delete iface;
            }

            bool operator()(Sequencer<Input>& seq, wrap::shared_ptr<Token<String, Kind, Vec>>& tok, int flag, Pos& pos, error<String>& err) {
                return iface ? iface->operator()(seq, tok, flag, pos, err) : throw std::bad_function_call();
            }

            template <class T__>
            const T__* type_assert() const {
                if (!iface) {
                    return nullptr;
                }
                return reinterpret_cast<const T__*>(iface->raw__(typeid(T__)));
            }

            template <class T__>
            T__* type_assert() {
                if (!iface) {
                    return nullptr;
                }
                return reinterpret_cast<T__*>(const_cast<void*>(iface->raw__(typeid(T__))));
            }

            Func(const Func&) = delete;

            Func& operator=(const Func&) = delete;
        };

    }  // namespace parser
}  // namespace utils
